version: '3.4'

services:
  voyager-rover:
    image: voyager-rover
    container_name: voyager-rover
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: 'no'
    stdin_open: true
    tty: true
    network_mode: host
    volumes:
      - .:/usr/src/app
    ports:
      - 9229:9229
    command: ['node', '--inspect=0.0.0.0:9229', './src/index.js']
