version: '3.9'
services:
  voyager-rover:
    image: voyager-rover
    container_name: voyager-rover
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: 'no'
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src/app
